# settings list

COMPANY_NAME = 'CtrlPyME'
COMPANY_SLOGAN = 'Press Ctrl + PyME to begin.'
COMPANY_LOGO_URL = ''

# the workflow determines how the employees will interact with the application
COMPANY_WORKFLOW = FLOW_BASIC

EXTRA_FIELD_1_NAME = ""
EXTRA_FIELD_2_NAME = ""
EXTRA_FIELD_3_NAME = ""

# if set true, only those users who have been created by the admin will have access to the online store.
USE_CLIENTS_WHITELIST = True

TICKET_FOOTER = T('This will be a ticket footer... soon')

# PAPER metrics in centimeters
PAPER_WIDTH = 21.59
PAPER_HEIGHT = 27.94
PAPER_MARGIN_TOP = 1
PAPER_MARGIN_RIGHT = 1
PAPER_MARGIN_BOTTOM = 1
PAPER_MARGIN_LEFT = 1

# labels
LABEL_SPACE_X = .5
LABEL_SPACE_Y = .5
LABEL_COLS = 3
LABEL_ROWS = 8
LABEL_SHOW_ITEM_NAME = True
LABEL_SHOW_PRICE = True
LABEL_WIDTH = (PAPER_WIDTH - (PAPER_MARGIN_LEFT + PAPER_MARGIN_RIGHT + LABEL_SPACE_X * (LABEL_COLS - 1))) / LABEL_COLS
LABEL_HEIGHT = (PAPER_HEIGHT - (PAPER_MARGIN_TOP + PAPER_MARGIN_BOTTOM + LABEL_SPACE_Y * (LABEL_ROWS - 1))) / LABEL_ROWS

PRIMARY_COLOR = '#0F5074'
PRIMARY_COLOR = '#0F6D74'
PRIMARY_COLOR = '#273C57'
PRIMARY_COLOR = '#505050'
PRIMARY_COLOR_TEXT = 'white'

ACCENT_COLOR = '#2FA871'
ACCENT_COLOR = '#502FA8'
ACCENT_COLOR = '#2375CA'
# ACCENT_COLOR = '#355CBC'
ACCENT_COLOR_TEXT = 'white'

BASE_COLOR = '#F3F3F3'
BASE_COLOR_TEXT = '#444'
